### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'toString')

### ISSUE THREAD

**Issue by spz2020** [computernewb/collabvm-1.2.ts#17]
log
> 
root@localhost:/srv/collabvm/collabvm-1.2.ts# npm run serve
> collabvm1.ts@1.0.0 serve
> node build/index.js
[3/16/2024, 1:20:04 PM] [INFO] CollabVM Server starting up
[3/16/2024, 1:20:06 PM] [INFO] QMP Connected
[3/16/2024, 1:20:07 PM] [INFO] VNC Connected
file:///srv/collabvm/collabvm-1.2.ts/build/WSServer.js:823
        var jpg64 = jpg.toString("base64");
                        ^

TypeError: Cannot read properties of undefined (reading 'toString')
    at WSServer.newrect (file:///srv/collabvm/collabvm-1.2.ts/build/WSServer.js:823:25)
    at QEMUVM.<anonymous> (file:///srv/collabvm/collabvm-1.2.ts/build/WSServer.js:81:51)
    at QEMUVM.emit (node:events:514:28)
    at file:///srv/collabvm/collabvm-1.2.ts/build/QEMUVM.js:191:22

Node.js v20.6.1
root@localhost:/srv/collabvm/collabvm-1.2.ts#
> 
ver  
Node.js v20.6.1

**Comment by spz2020** [comment]
There's no need. I've fixed it
apt-get install build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev
