### ISSUE TITLE
CollabVM Bans will not Function RunCPU errors.

### ISSUE THREAD

**Issue by darkmode120** [computernewb/collabvm-1.2.ts#34]
Hi so I am stuck on this error and Idk how to fix it.
The error is:
{"level":30,"time":1732999235710,"pid":15890,"hostname":"debian","msg":"CollabVM Server starting up"}
{"level":50,"time":1732999235722,"pid":15890,"hostname":"debian","name":"CVMTS/CGroup","error":{"errno":-2,"code":"ENOENT","syscall":"write"},"msg":"Could not provide cpuset controller to subtree. runOnCpus will not function."}
{"level":40,"time":1732999235721,"pid":15890,"hostname":"debian","msg":"Neither cvmban nor ban command are configured. Bans will not function."}
node:fs:2342
    return binding.writeFileUtf8(
                   ^

Error: ENOENT: no such file or directory, write
    at writeFileSync (node:fs:2342:20)
    at CGroup.InitControllers (file:///home/darkmode/Downloads/collabvm-1.2.ts/cvmts/dist/util/cgroup.js:38:17)
    at new QemuResourceLimitedLauncher (file:///home/darkmode/Downloads/collabvm-1.2.ts/cvmts/dist/vm/qemu_launcher.js:93:23)
    at new QemuVMShim (file:///home/darkmode/Downloads/collabvm-1.2.ts/cvmts/dist/vm/qemu.js:17:36)
    at start (file:///home/darkmode/Downloads/collabvm-1.2.ts/cvmts/dist/index.js:71:18)
    at file:///home/darkmode/Downloads/collabvm-1.2.ts/cvmts/dist/index.js:98:1
    at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:323:24)
    at async loadESM (node:internal/process/esm_loader:28:7)
    at async handleMainPromise (node:internal/modules/run_main:120:12) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'write'
}

Node.js v21.7.3

How do I fix it?

**Comment by modeco80** [comment]
Update to at least fe82973b9f3e2a53af2183816c39ed225c12a022 which makes resource control failures soft/reporting only, or (as directed in the example configuration relatively clearly), comment the `vm.resouceLimits` table out to disable resource control.

**Comment by darkmode120** [comment]
Okay thank you.
