### ISSUE TITLE
what? idk. ISSUES OF DIS PLS HELP. - Running copy of September 3rd, 2023

### ISSUE THREAD

**Issue by gunawan092w** [computernewb/collabvm-1.2.ts#8]
It works fine for copy of June 6, 2023 when i was on Windows
now today, im running this at latest commit, and it doesn;t work. 
can u fix this?

Ubuntu Server 22.04 LTS Jammy AWS
```
root@ip-172-31-21-57:/home/ubuntu# rm collabvm-1.2.ts/ -r
root@ip-172-31-21-57:/home/ubuntu# git clone https://github.com/computernewb/collabvm-1.2.ts
Cloning into 'collabvm-1.2.ts'...
remote: Enumerating objects: 311, done.
remote: Counting objects: 100% (110/110), done.
remote: Compressing objects: 100% (23/23), done.
remote: Total 311 (delta 101), reused 87 (delta 87), pack-reused 201
Receiving objects: 100% (311/311), 191.76 KiB | 2.26 MiB/s, done.
Resolving deltas: 100% (214/214), done.
root@ip-172-31-21-57:/home/ubuntu# cd collabvm-1.2.ts/
root@ip-172-31-21-57:/home/ubuntu/collabvm-1.2.ts# mv config.example.toml config.toml
root@ip-172-31-21-57:/home/ubuntu/collabvm-1.2.ts# npm i

added 171 packages, and audited 172 packages in 32s

23 packages are looking for funding
  run `npm fund` for details

8 moderate severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
root@ip-172-31-21-57:/home/ubuntu/collabvm-1.2.ts# npm run build

> collabvm1.ts@1.0.0 build
> tsc

root@ip-172-31-21-57:/home/ubuntu/collabvm-1.2.ts# npm run serve

> collabvm1.ts@1.0.0 serve
> node build/index.js

file:///home/ubuntu/collabvm-1.2.ts/build/QEMUVM.js:73
            this.qemuProcess.stderr?.on('data', (d) => log("ERROR", `QEMU sent to stderr: ${d.toString()}`));
                                    ^

SyntaxError: Unexpected token '.'
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
root@ip-172-31-21-57:/home/ubuntu/collabvm-1.2.ts#
```

**Comment by MDMCK10** [comment]
Update your version of Node.js by following the instructions here: https://github.com/nodesource/distributions#installation-instructions

**Comment by gunawan092w** [comment]
```
root@ip-172-31-21-57:/home/ubuntu/collabvm-1.2.ts# sudo apt-get install nodejs -y
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following packages were automatically installed and are no longer required:
  libc-ares2 libnode72
Use 'sudo apt autoremove' to remove them.
The following packages will be upgraded:
  nodejs
1 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/31.0 MB of archives.
After this operation, 193 MB of additional disk space will be used.
(Reading database ... 186129 files and directories currently installed.)
Preparing to unpack .../nodejs_20.6.1-1nodesource1_amd64.deb ...
Unpacking nodejs (20.6.1-1nodesource1) over (12.22.9~dfsg-1ubuntu3) ...
Setting up nodejs (20.6.1-1nodesource1) ...
Processing triggers for man-db (2.10.2-1) ...
Scanning processes...
Scanning linux images...

Running kernel seems to be up-to-date.

No services need to be restarted.

No containers need to be restarted.

No user sessions are running outdated binaries.

No VM guests are running outdated hypervisor (qemu) binaries on this host.
root@ip-172-31-21-57:/home/ubuntu/collabvm-1.2.ts# node --version
v20.6.1
root@ip-172-31-21-57:/home/ubuntu/collabvm-1.2.ts# node ./build/index.js
node:internal/modules/cjs/loader:1327
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: The module '/home/ubuntu/collabvm-1.2.ts/node_modules/canvas/build/Release/canvas.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 72. This version of Node.js requires
NODE_MODULE_VERSION 115. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Module._extensions..node (node:internal/modules/cjs/loader:1327:18)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:130:18)
    at Object.<anonymous> (/home/ubuntu/collabvm-1.2.ts/node_modules/canvas/lib/bindings.js:3:18)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12) {
  code: 'ERR_DLOPEN_FAILED'
}

Node.js v20.6.1
root@ip-172-31-21-57:/home/ubuntu/collabvm-1.2.ts# npm rebuild
rebuilt dependencies successfully
root@ip-172-31-21-57:/home/ubuntu/collabvm-1.2.ts# node ./build/index.js
[9/10/2023, 3:22:50 PM] [INFO] CollabVM Server starting up
root@ip-172-31-21-57:/home/ubuntu/collabvm-1.2.ts#
```

**Comment by gunawan092w** [comment]
> Update your version of Node.js by following the instructions here: https://github.com/nodesource/distributions#installation-instructions

i updated node.js, then when i run the build, it only show the output `CollabVM Server starting up`

**Comment by MDMCK10** [comment]
Make sure QEMU is installed on the host you're trying to run the server on: `sudo apt install qemu-system-x86 -y`

**Comment by gunawan092w** [comment]
> Make sure QEMU is installed on the host you're trying to run the server on: `sudo apt install qemu-system-x86 -y`

thank you so much, it works now :DDDDD
